#!/bin/bash

############################################################
#begin user configs
############################################################

# your cs account username
#
# mandatory if it is different from current $USER on your
# machine. otherwise you can leave it empty.
CS_USER=""

# one of the public cs linux machine
#
# if this one is not working, try another one.
CS_SERVER="chu-totoro.cs.utexas.edu"

# if you are not login using ssh key, consider using it now.
# see "man ssh" for more info.

############################################################
#end user configs
############################################################

EE_BAD_PARAM=1
EE_UNALIAS_FAILURE=2

CONF="$HOME/.turninrc"

if [ -e "$CONF" ]
then
	. $CONF
fi

#build ssh command according to user preference
if ! [ -z "$CS_USER" ]
then
	CS_SERVER="${CS_USER}@${CS_SERVER}"
fi

SSH="ssh -x $CS_SERVER"

print_help () {
	echo "turnin - local turnin, a wrapper of cs turnin"
	echo "Usage: turnin [grader] [hw] [FILE]...      submit files"
	echo "       turnin ls [grader] [hw]             list submitted files"
	echo
	echo "       turnin alias [alias] [grader]       give grader a new name"
	echo "       turnin unalias [alias]              remove the alias"
	echo "       turnin alias                        list known aliases"
	echo
	echo
	echo "If you are commiting a dir, don't add / at the end of the dir name."
	echo 
	echo "Report bugs to Yuanle Song <sylecn@gmail.com>."
}

# main()
case "${1:-''}" in
	'ls'|'--list')
		subcommand="ls"
		shift
		;;
	'submit'|'--submit')
		subcommand="submit"
		shift
		;;
	'alias'|'--alias')
		subcommand="alias"
		shift
		if [ $# -eq 0 ]
		then
			subcommand="listalias"
		fi
		;;
	'unalias'|'--unalias')
		subcommand="unalias"
		shift
		;;
	'help'|'--help'|'-h')
		print_help
		exit 0
		;;
	*)
		subcommand="submit"
		;;
esac

case "$subcommand" in
	'ls')
		grader="$1"
		hw="$2"
		if [ -z "$grader" ] || [ -z "$hw" ]
		then
			echo "turnin: error: ls: not enough parameters."
			echo "run turnin --help for more info."
			exit $EE_BAD_PARAM
		fi
		$SSH "turnin --list $grader $hw"
		;;
	'submit')
		grader="$1"
		hw="$2"
		shift 2
		if [ -z "$grader" ] || [ -z "$hw" ] || [ -z "$*" ]
		then
			echo "turnin: error: submit: not enough parameters"
			echo "run turnin --help for more info."
			exit $EE_BAD_PARAM
		fi

		#transfer files using rsync, then submit
		remote_dir="~/.turnin/$grader/$hw/"
		$SSH "mkdir -p $remote_dir"
		rsync -i -a -r $* $CS_SERVER:$remote_dir
		$SSH "cd $remote_dir && turnin $grader $hw $*"
		;;
	'alias')
		newname="$1"
		grader="$2"
		if [ -z "$newname" ] || [ -z "$grader" ]
		then
			echo "turnin: error: alias: not enough parameters"
			echo "run turnin --help for more info."
			exit $EE_BAD_PARAM
		fi
		echo "# alias ${newname}=${grader}" >> $CONF
		exit 0
		;;
	'unalias')
		newname="$1"
		if [ -z "$newname" ]
		then
			echo "turnin: error: unalias: not enough parameters"
			echo "run turnin --help for more info."
			exit $EE_BAD_PARAM
		fi
		grep -q "alias ${newname}=" $CONF
		if [ $? -eq 0 ]
		then
			mv $CONF $CONF.bak
			sed "/# alias ${newname}=/d" $CONF.bak > $CONF
			exit 0
		else
			echo "turnin: error: unalias: ${newname} not found"
			exit $EE_UNALIAS_FAILURE
		fi
		;;
	'listalias')
		[ -e "$CONF" ] || exit 0
		grep "=[^\"]" $CONF | cut -d " " --complement -f 1
		exit 0
		;;
	*)
		#never reach here
		echo "turnin: warning: bad subcommand: $subcommand"
		exit $EE_BAD_PARAM
		;;
esac


